// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qu97DMHR98hCuJrStiGwpdxtc3R7_9Q',
    appId: '1:44222883420:web:a5dc34dd085fd9dbbbe899',
    messagingSenderId: '44222883420',
    projectId: 'sushi-f3dbc',
    authDomain: 'sushi-f3dbc.firebaseapp.com',
    storageBucket: 'sushi-f3dbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4fgC_91bGzmoLf3F0tPUIlu6wjsVkXU',
    appId: '1:44222883420:android:f013cbd873138d2dbbe899',
    messagingSenderId: '44222883420',
    projectId: 'sushi-f3dbc',
    storageBucket: 'sushi-f3dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJtrZ53xJGBqQPvCXAiobIias_rBcO4v8',
    appId: '1:44222883420:ios:8d0e22c3487f68a9bbe899',
    messagingSenderId: '44222883420',
    projectId: 'sushi-f3dbc',
    storageBucket: 'sushi-f3dbc.appspot.com',
    iosBundleId: 'com.example.sushRoys',
  );
}
